name: CI Checks (Lint, TypeScript)

on:
  pull_request:
    branches:
      - "**" # ✅ Runs on all PRs
  push:
    branches:
      - main # ✅ Runs only when code is merged into `main`

jobs:
  lint:
    name: ESLint Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  type-check:
    name: TypeScript Type Checking
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn type-check
