name: Manual Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Deploy to Vercel
        run: |
          yarn global add vercel
          vercel --token ${{ env.VERCEL_TOKEN }} --prod
